using System.Collections.Generic;

namespace LightControl
{
    /// <summary>
    /// Generated by http://json2csharp.com/
    /// </summary>
    public class Other
    {
        public string Rcgroup { get; set; }
        public string Manufacturer { get; set; }
        public string Capability { get; set; }
        public string Bulbpower { get; set; }
    }

    public class Device
    {
        public string Did { get; set; }
        public string Known { get; set; }
        public string Lock { get; set; }
        public string State { get; set; }
        public string Level { get; set; }
        public string Node { get; set; }
        public string Port { get; set; }
        public string Nodetype { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public string Colorid { get; set; }
        public string Type { get; set; }
        public string Rangemin { get; set; }
        public string Rangemax { get; set; }
        public string Power { get; set; }
        public string Poweravg { get; set; }
        public string Energy { get; set; }
        public string Score { get; set; }
        public string Productid { get; set; }
        public string Prodbrand { get; set; }
        public string Prodmodel { get; set; }
        public string Prodtype { get; set; }
        public string Prodtypeid { get; set; }
        public string Classid { get; set; }
        public string Class { get; set; }
        public string Subclassid { get; set; }
        public string Subclass { get; set; }
        public Other Other { get; set; }
    }

    public class Room
    {
        public string Rid { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public string Known { get; set; }
        public string Type { get; set; }
        public string Color { get; set; }
        public string Colorid { get; set; }
        public string Img { get; set; }
        public string Power { get; set; }
        public string Poweravg { get; set; }
        public string Energy { get; set; }
        public Device Device { get; set; }

        /// <summary>
        /// Objects are equal only if rid and name are the same
        /// </summary>
        /// <param name="obj"></param>
        /// <returns></returns>
        public override bool Equals(object obj)
        {
            if (obj == null || GetType() != obj.GetType())
                return false;

            var p = (Room)obj;
            return (Rid == p.Rid) && (Name.Equals(p.Name));
        }

        /// <summary>
        /// Use default hash code for now
        /// </summary>
        /// <returns></returns>
        public override int GetHashCode()
        {
            return base.GetHashCode();
        }
    }

    public class Gip
    {
        public string Version { get; set; }
        public string Rc { get; set; }
        public List<Room> Room { get; set; }
    }

    public class Gdata
    {
        public Gip Gip { get; set; }
    }

    public class Gwrcmd
    {
        public string Gcmd { get; set; }
        public Gdata Gdata { get; set; }
    }

    public class Gwrcmds
    {
        public Gwrcmd Gwrcmd { get; set; }
    }

    public class GwrObject
    {
        public Gwrcmds Gwrcmds { get; set; }

        /// <summary>
        /// Returns true if the rooms record is intact
        /// </summary>
        /// <returns></returns>
        public bool HasRooms()
        {

            var count = Gwrcmds?.Gwrcmd?.Gdata?.Gip?.Room?.Count;
            return count > 0;
        }
    }
}
